{"name": "test_specific_feature", "status": "failed", "statusDetails": {"message": "Failed: Test failed with message: 先前的充值申请正在处理中，请勿重复提交！#Do Not Do Payment Again Before Your Order Is Finished#還有充值申請正在處理中，請稍後再提交。#อย่าชำระเงินอีกก่อนที่คำสั่งซื้อของคุณจะเสร็จสิ้น#Não faça o pagamento novamente antes que seu pedido seja concluído", "trace": "@pytest.mark.asyncio\n    async def test_specific_feature():\n        playwright, browser, context = await setup_browser()  # 使用默认设备iPhone 11\n        test_failed = False\n        fail_message = \"\"\n        try:\n            page = await load_and_check_page(context)\n            print(\"Page loaded successfully.\")\n    \n            await login(page, \"all24042501\", \"396012\")  # 使用公共登录函数\n    \n            with step(\"导航到个人中心\"):\n                await page.click(\"div.label:has-text('個人中心')\")\n                await asyncio.sleep(2)\n                await take_screenshot_and_attach(page, \"after_navigate_to_personal_center\")\n    \n            with step(\"点击存款\"):\n                await page.click(\"div.label:has-text('存款')\")\n                await asyncio.sleep(2)\n                await take_screenshot_and_attach(page, \"after_click_deposit\")\n    \n            with step(\"选择数字乐\"):\n                await page.click(\"div.am-list-content:has-text('數字樂')\")\n                await asyncio.sleep(2)\n                await take_screenshot_and_attach(page, \"after_select_bank_transfer\")\n    \n            with step(\"输入充值金额\"):\n                await page.fill(\"input#chargeAmount.fc-red\", \"100\")\n                await asyncio.sleep(2)\n                await take_screenshot_and_attach(page, \"after_enter_deposit_amount\")\n    \n            async def handle_response(response):\n                if response.url == \"https://wap-q6.qbpink01.com/payment/frontend/doPay\":\n                    json_data = await response.json()\n                    print(f\"Response from doPay: {json_data}\")\n                    if json_data.get('code') == '2313':\n                        nonlocal test_failed, fail_message\n                        test_failed = True\n                        fail_message = f\"Test failed with message: {\n                            json_data.get('msg')}\"\n    \n            page.on('response', handle_response)\n    \n            with step(\"点击下一步按钮\"):\n                await page.click(\"a.submitBtn:has-text('下一步')\")\n                await asyncio.sleep(2)\n                await take_screenshot_and_attach(page, \"after_confirm_deposit\")\n    \n            with step(\"确认充值完成\"):\n                await page.click(\"a:has-text('已完成充值')\")\n                await asyncio.sleep(2)\n                await take_screenshot_and_attach(page, \"after_confirm_deposit\")\n    \n        except Exception as e:\n            print(f\"An error occurred: {e}\")\n            if page is not None:\n                await take_screenshot_and_attach(page, \"error_during_test\")\n        finally:\n            # 注销监听器\n            page.remove_listener('response', handle_response)\n            if browser is not None:\n                await browser.close()\n            if playwright is not None:\n                await playwright.stop()\n            if test_failed:\n>               pytest.fail(fail_message)\nE               Failed: Test failed with message: 先前的充值申请正在处理中，请勿重复提交！#Do Not Do Payment Again Before Your Order Is Finished#還有充值申請正在處理中，請稍後再提交。#อย่าชำระเงินอีกก่อนที่คำสั่งซื้อของคุณจะเสร็จสิ้น#Não faça o pagamento novamente antes que seu pedido seja concluído\n\nbasic_module\\test_digital music.py:72: Failed"}, "steps": [{"name": "导航到个人中心", "status": "passed", "attachments": [{"name": "after_navigate_to_personal_center", "source": "9c10dc8f-0716-4195-aee6-04f175c3c007-attachment.png", "type": "image/png"}], "start": 1716456276232, "stop": 1716456279950}, {"name": "点击存款", "status": "passed", "attachments": [{"name": "after_click_deposit", "source": "778286a3-5d28-41be-8aee-0c7d03e6c3a1-attachment.png", "type": "image/png"}], "start": 1716456279950, "stop": 1716456282139}, {"name": "选择数字乐", "status": "passed", "attachments": [{"name": "after_select_bank_transfer", "source": "770ddde5-c5b7-48f2-81a2-73a213f11579-attachment.png", "type": "image/png"}], "start": 1716456282139, "stop": 1716456284326}, {"name": "输入充值金额", "status": "passed", "attachments": [{"name": "after_enter_deposit_amount", "source": "62face12-d250-4be0-be24-468b1c14ff74-attachment.png", "type": "image/png"}], "start": 1716456284326, "stop": 1716456286468}, {"name": "点击下一步按钮", "status": "passed", "attachments": [{"name": "after_confirm_deposit", "source": "a7f85dc0-680e-4886-bb22-d87d5f25e9bd-attachment.png", "type": "image/png"}], "start": 1716456286473, "stop": 1716456288637}, {"name": "确认充值完成", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Page.click: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"a:has-text('已完成充值')\")\n\n", "trace": "  File \"C:\\Users\\luekc\\Desktop\\Q6\\basic_module\\test_digital music.py\", line 56, in test_specific_feature\n    await page.click(\"a:has-text('已完成充值')\")\n  File \"C:\\Users\\luekc\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\playwright\\async_api\\_generated.py\", line 9444, in click\n    await self._impl_obj.click(\n  File \"C:\\Users\\luekc\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\playwright\\_impl\\_page.py\", line 753, in click\n    return await self._main_frame.click(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\luekc\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\playwright\\_impl\\_frame.py\", line 488, in click\n    await self._channel.send(\"click\", locals_to_params(locals()))\n  File \"C:\\Users\\luekc\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\luekc\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 513, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "start": 1716456288637, "stop": 1716456318657}], "attachments": [{"name": "error_during_test", "source": "bd8412d1-e7fd-4701-951b-790447380d3b-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "3c58fe14-49a8-4884-940d-a11aaf297059-attachment.txt", "type": "text/plain"}], "start": 1716456259242, "stop": 1716456318996, "uuid": "022bc716-f279-49da-9c91-09dc8548a469", "historyId": "25d87ba0cfa6d2772725fc948070e326", "testCaseId": "25d87ba0cfa6d2772725fc948070e326", "fullName": "basic_module.test_digital music#test_specific_feature", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "basic_module"}, {"name": "suite", "value": "test_digital music"}, {"name": "host", "value": "Luke"}, {"name": "thread", "value": "31484-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "basic_module.test_digital music"}]}